---
  - name: register swap_file variable
    stat: path={{ swap_location }}
    register: swap_file

  - name: create swap file
    command: fallocate -l {{ swap_size }}M {{ swap_location }}
    when: swap_file.stat.exists == False

  - name: format swap file
    command: mkswap {{ swap_location }}
    when: swap_file.stat.exists == False

  - name: change swap file permissions
    file: path={{ swap_location }} owner=root group=root mode=0600
    when: swap_file.stat.exists == False

  - name: enable swap
    command: swapon {{ swap_location }}
    when: swap_file.stat.exists == False

  - name: swap file is in /etc/fstab
    lineinfile: dest=/etc/fstab line="{{ swap_location }}   none    swap    sw    0   0" state=present
    when: swap_file.stat.exists == True

