---

- name: install self signed certificate and key
  sudo: True
  copy: >
    src="{{ item }}"
    dest="{{ ssl_path }}/{{ item }}"
    owner={{ service_user }}
    group={{ service_group }}
    mode=0644
  with_items:
    - "server.key"
    - "server.crt"
