---
# setup gunicorn in the prepared virtualenv

- name: install gunicorn
  pip: virtualenv="{{ virtualenv_path }}"
       executable="{{ virtualenv_path }}/bin/pip"
       name=gunicorn

- name: configure gunicorn
  template: >
    src="gunicorn.py.j2"
    dest="{{ install_path }}/gunicorn.py"
    owner={{ service_user }}
    group={{ service_group }}
    mode=0644
    backup=yes
  notify:
    - restart django app
