---
# install the latest django and create a new project structure

- name: install django to create new project
  pip: >
    virtualenv="{{ virtualenv_path }}"
    executable="{{ virtualenv_path }}/bin/pip"
    name="Django"
    state=latest

- name: create new django project from template
  become_user: "{{ service_user }}"
  shell: >
    {{ virtualenv_path }}/bin/python -m django startproject --template={{ django_project_template }} {{ service_name }} {{ source_path }}

- name: make manage.py executeable
  become_user: "{{ service_user }}"
  file: >
    path="{{ source_path }}/manage.py"
    owner={{ service_user }}
    group={{ service_group }}
    mode=0755
