---
# install application sources and configure local settings

- include: 10-install.yml
  tags: install

- include: 20-update_requirements.yml
  tags: update_requirements

- include: 30-update_settings.yml
  tags: update_settings

- include: 40-setup_database.yml
  tags: setup_database

- include: 50-post_install.yml
  become_user: "{{ service_user }}"
  tags: post_install

- include: 90-fixtures.yml
  become_user: "{{ service_user }}"
  tags: fixtures
