---
# prepare python2 and create a service virtualenv

- name: install python2 headers
  become_user: 'root'
  apt: name={{ item }} state=latest update_cache=yes cache_valid_time=600
  with_items:
    - python-dev

- name: create python2 virtualenv
  command: virtualenv -p /usr/bin/python2 {{ virtualenv_path }}
  args:
    creates: "{{ virtualenv_path }}/bin/python2"
